-- Chemlab Hostinger Backend - Stage 3 Admin Resource Tools

CREATE TABLE IF NOT EXISTS memory_decks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  description TEXT NULL,
  language VARCHAR(20) DEFAULT 'en',
  difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'beginner',
  status ENUM('draft','published','archived') DEFAULT 'draft',
  source_type ENUM('NCERT','CUSTOM','SIMULATION','AI_ASSISTED') DEFAULT 'CUSTOM',
  source_reference TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY memory_decks_uuid_unique (uuid),
  UNIQUE KEY memory_decks_slug_unique (slug),
  KEY memory_decks_class_index (class_id),
  KEY memory_decks_chapter_index (chapter_id),
  KEY memory_decks_topic_index (topic_id),
  KEY memory_decks_resource_index (resource_id),
  KEY memory_decks_status_index (status),
  CONSTRAINT memory_decks_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT memory_decks_approved_by_fk FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_cards (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  deck_id BIGINT UNSIGNED NOT NULL,
  front VARCHAR(255) NOT NULL,
  back TEXT NOT NULL,
  hint TEXT NULL,
  explanation TEXT NULL,
  difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'beginner',
  card_type ENUM('concept','formula','definition','mistake','application') DEFAULT 'concept',
  mistake_type VARCHAR(120) NULL,
  source_reference TEXT NULL,
  order_index INT DEFAULT 0,
  status ENUM('draft','published','archived') DEFAULT 'published',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY memory_cards_deck_front_unique (deck_id, front),
  KEY memory_cards_deck_index (deck_id),
  KEY memory_cards_status_index (status),
  CONSTRAINT memory_cards_deck_fk FOREIGN KEY (deck_id) REFERENCES memory_decks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quick_drills (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  description TEXT NULL,
  language VARCHAR(20) DEFAULT 'en',
  difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'beginner',
  estimated_minutes INT DEFAULT 5,
  status ENUM('draft','published','archived') DEFAULT 'draft',
  source_type ENUM('NCERT','CUSTOM','SIMULATION','AI_ASSISTED') DEFAULT 'CUSTOM',
  source_reference TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY quick_drills_uuid_unique (uuid),
  UNIQUE KEY quick_drills_slug_unique (slug),
  KEY quick_drills_class_index (class_id),
  KEY quick_drills_chapter_index (chapter_id),
  KEY quick_drills_topic_index (topic_id),
  KEY quick_drills_resource_index (resource_id),
  KEY quick_drills_status_index (status),
  CONSTRAINT quick_drills_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT quick_drills_approved_by_fk FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quiz_questions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  drill_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  question_text TEXT NOT NULL,
  question_type ENUM('mcq','multi_select','true_false','short_answer') DEFAULT 'mcq',
  options_json JSON NULL,
  correct_answer_json JSON NULL,
  explanation TEXT NULL,
  hint TEXT NULL,
  difficulty ENUM('beginner','intermediate','advanced') DEFAULT 'beginner',
  mistake_type VARCHAR(120) NULL,
  source_reference TEXT NULL,
  order_index INT DEFAULT 0,
  status ENUM('draft','published','archived') DEFAULT 'published',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY quiz_questions_drill_text_unique (drill_id, question_text(190)),
  KEY quiz_questions_drill_index (drill_id),
  KEY quiz_questions_class_index (class_id),
  KEY quiz_questions_chapter_index (chapter_id),
  KEY quiz_questions_topic_index (topic_id),
  KEY quiz_questions_status_index (status),
  CONSTRAINT quiz_questions_drill_fk FOREIGN KEY (drill_id) REFERENCES quick_drills(id) ON DELETE CASCADE,
  CONSTRAINT quiz_questions_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT quiz_questions_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
  CONSTRAINT quiz_questions_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE SET NULL,
  CONSTRAINT quiz_questions_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS concept_maps (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL,
  description TEXT NULL,
  map_json JSON NULL,
  status ENUM('draft','published','archived') DEFAULT 'draft',
  source_reference TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY concept_maps_uuid_unique (uuid),
  UNIQUE KEY concept_maps_slug_unique (slug),
  KEY concept_maps_class_index (class_id),
  KEY concept_maps_chapter_index (chapter_id),
  KEY concept_maps_topic_index (topic_id),
  KEY concept_maps_status_index (status),
  CONSTRAINT concept_maps_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT concept_maps_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
  CONSTRAINT concept_maps_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE SET NULL,
  CONSTRAINT concept_maps_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL,
  CONSTRAINT concept_maps_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT concept_maps_approved_by_fk FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mistake_patterns (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  mistake_key VARCHAR(190) NOT NULL,
  title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  correction TEXT NULL,
  example TEXT NULL,
  severity ENUM('low','medium','high') DEFAULT 'medium',
  status ENUM('draft','published','archived') DEFAULT 'published',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY mistake_patterns_key_unique (mistake_key),
  KEY mistake_patterns_class_index (class_id),
  KEY mistake_patterns_chapter_index (chapter_id),
  KEY mistake_patterns_topic_index (topic_id),
  KEY mistake_patterns_resource_index (resource_id),
  KEY mistake_patterns_status_index (status),
  CONSTRAINT mistake_patterns_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT mistake_patterns_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL,
  CONSTRAINT mistake_patterns_chapter_fk FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE SET NULL,
  CONSTRAINT mistake_patterns_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL,
  CONSTRAINT mistake_patterns_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
