-- Chemlab Hostinger Backend - Stage 4 Learning Intelligence

CREATE TABLE IF NOT EXISTS resource_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  session_id VARCHAR(100) NULL,
  resource_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_type VARCHAR(80) NULL,
  started_at DATETIME NOT NULL,
  ended_at DATETIME NULL,
  duration_seconds INT DEFAULT 0,
  completed TINYINT(1) DEFAULT 0,
  completion_percent INT DEFAULT 0,
  exit_reason VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY resource_sessions_uuid_unique (uuid),
  KEY resource_sessions_user_id_index (user_id),
  KEY resource_sessions_resource_id_index (resource_id),
  KEY resource_sessions_class_index (class_id),
  KEY resource_sessions_created_index (created_at),
  CONSTRAINT resource_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT resource_sessions_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simulation_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  session_id VARCHAR(100) NULL,
  simulation_slug VARCHAR(190) NOT NULL,
  resource_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  started_at DATETIME NOT NULL,
  ended_at DATETIME NULL,
  duration_seconds INT DEFAULT 0,
  completed TINYINT(1) DEFAULT 0,
  highest_level VARCHAR(100) NULL,
  mistakes_count INT DEFAULT 0,
  hints_used INT DEFAULT 0,
  enjoyment_rating TINYINT NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY simulation_sessions_uuid_unique (uuid),
  KEY simulation_sessions_user_id_index (user_id),
  KEY simulation_sessions_slug_index (simulation_slug),
  KEY simulation_sessions_resource_index (resource_id),
  KEY simulation_sessions_created_index (created_at),
  CONSTRAINT simulation_sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT simulation_sessions_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simulation_step_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  simulation_session_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  simulation_slug VARCHAR(190) NOT NULL,
  step_key VARCHAR(190) NOT NULL,
  event_name VARCHAR(150) NOT NULL,
  success TINYINT(1) NULL,
  mistake_key VARCHAR(190) NULL,
  duration_seconds INT DEFAULT 0,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY simulation_step_session_index (simulation_session_id),
  KEY simulation_step_slug_index (simulation_slug),
  KEY simulation_step_event_index (event_name),
  KEY simulation_step_mistake_index (mistake_key),
  CONSTRAINT simulation_step_session_fk FOREIGN KEY (simulation_session_id) REFERENCES simulation_sessions(id) ON DELETE SET NULL,
  CONSTRAINT simulation_step_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mistake_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  session_id VARCHAR(100) NULL,
  mistake_key VARCHAR(190) NOT NULL,
  mistake_pattern_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  simulation_slug VARCHAR(190) NULL,
  question_id BIGINT UNSIGNED NULL,
  severity ENUM('low','medium','high') DEFAULT 'medium',
  student_answer TEXT NULL,
  correct_answer TEXT NULL,
  feedback_shown TEXT NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY mistake_events_user_index (user_id),
  KEY mistake_events_key_index (mistake_key),
  KEY mistake_events_topic_index (topic_id),
  KEY mistake_events_resource_index (resource_id),
  CONSTRAINT mistake_events_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT mistake_events_pattern_fk FOREIGN KEY (mistake_pattern_id) REFERENCES mistake_patterns(id) ON DELETE SET NULL,
  CONSTRAINT mistake_events_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL,
  CONSTRAINT mistake_events_question_fk FOREIGN KEY (question_id) REFERENCES quiz_questions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  deck_id BIGINT UNSIGNED NOT NULL,
  card_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  rating ENUM('easy','good','hard','forgot') NOT NULL,
  response_time_ms INT NULL,
  review_mode ENUM('learn','review','mistake_fix') DEFAULT 'learn',
  next_review_at DATETIME NULL,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY memory_reviews_user_index (user_id),
  KEY memory_reviews_deck_index (deck_id),
  KEY memory_reviews_card_index (card_id),
  CONSTRAINT memory_reviews_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT memory_reviews_deck_fk FOREIGN KEY (deck_id) REFERENCES memory_decks(id) ON DELETE CASCADE,
  CONSTRAINT memory_reviews_card_fk FOREIGN KEY (card_id) REFERENCES memory_cards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_card_progress (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  deck_id BIGINT UNSIGNED NOT NULL,
  card_id BIGINT UNSIGNED NOT NULL,
  ease_score DECIMAL(5,2) DEFAULT 2.50,
  review_count INT DEFAULT 0,
  forgot_count INT DEFAULT 0,
  hard_count INT DEFAULT 0,
  last_rating VARCHAR(20) NULL,
  last_reviewed_at DATETIME NULL,
  next_review_at DATETIME NULL,
  mastered TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY memory_card_progress_user_card_unique (user_id, card_id),
  KEY memory_card_progress_anonymous_card_index (anonymous_id, card_id),
  KEY memory_card_progress_deck_index (deck_id),
  CONSTRAINT memory_card_progress_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT memory_card_progress_deck_fk FOREIGN KEY (deck_id) REFERENCES memory_decks(id) ON DELETE CASCADE,
  CONSTRAINT memory_card_progress_card_fk FOREIGN KEY (card_id) REFERENCES memory_cards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  drill_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  started_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  duration_seconds INT DEFAULT 0,
  score INT DEFAULT 0,
  total_questions INT DEFAULT 0,
  correct_count INT DEFAULT 0,
  wrong_count INT DEFAULT 0,
  hints_used INT DEFAULT 0,
  completed TINYINT(1) DEFAULT 0,
  metadata JSON NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY quiz_attempts_uuid_unique (uuid),
  KEY quiz_attempts_user_index (user_id),
  KEY quiz_attempts_drill_index (drill_id),
  KEY quiz_attempts_created_index (created_at),
  CONSTRAINT quiz_attempts_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT quiz_attempts_drill_fk FOREIGN KEY (drill_id) REFERENCES quick_drills(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS quiz_answers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  attempt_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  selected_answer_json JSON NULL,
  correct_answer_json JSON NULL,
  is_correct TINYINT(1) DEFAULT 0,
  response_time_ms INT NULL,
  hint_used TINYINT(1) DEFAULT 0,
  mistake_key VARCHAR(190) NULL,
  explanation_shown TEXT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY quiz_answers_attempt_question_unique (attempt_id, question_id),
  KEY quiz_answers_user_index (user_id),
  KEY quiz_answers_question_index (question_id),
  KEY quiz_answers_mistake_index (mistake_key),
  CONSTRAINT quiz_answers_attempt_fk FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,
  CONSTRAINT quiz_answers_question_fk FOREIGN KEY (question_id) REFERENCES quiz_questions(id) ON DELETE CASCADE,
  CONSTRAINT quiz_answers_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resource_feedback (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  resource_id BIGINT UNSIGNED NULL,
  resource_type VARCHAR(80) NULL,
  rating TINYINT NULL,
  reaction ENUM('loved','useful','confusing','too_hard','boring') NULL,
  comment TEXT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY resource_feedback_resource_index (resource_id),
  KEY resource_feedback_user_index (user_id),
  CONSTRAINT resource_feedback_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT resource_feedback_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chem_shastri_question_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  anonymous_id VARCHAR(100) NULL,
  conversation_id BIGINT UNSIGNED NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  simulation_slug VARCHAR(190) NULL,
  question_text LONGTEXT NULL,
  normalized_question_hash VARCHAR(255) NULL,
  intent VARCHAR(100) NULL,
  mode VARCHAR(80) NULL,
  answer_source VARCHAR(80) NULL,
  provider VARCHAR(80) NULL,
  model VARCHAR(100) NULL,
  helpful_rating ENUM('helpful','not_helpful','too_hard','too_long','wrong') NULL,
  cost_inr_est DECIMAL(10,4) DEFAULT 0,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY chem_shastri_question_logs_created_at_index (created_at),
  KEY chem_shastri_question_logs_topic_id_index (topic_id),
  KEY chem_shastri_question_logs_hash_index (normalized_question_hash),
  CONSTRAINT chem_shastri_question_logs_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chem_shastri_question_logs_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS student_topic_mastery (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NOT NULL,
  mastery_score DECIMAL(5,2) DEFAULT 0,
  confidence ENUM('low','medium','high') DEFAULT 'low',
  resources_completed INT DEFAULT 0,
  drills_completed INT DEFAULT 0,
  memory_cards_mastered INT DEFAULT 0,
  mistakes_count INT DEFAULT 0,
  last_activity_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY student_topic_mastery_user_topic_unique (user_id, topic_id),
  KEY student_topic_mastery_class_index (class_id),
  CONSTRAINT student_topic_mastery_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT student_topic_mastery_topic_fk FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS daily_learning_rollups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rollup_date DATE NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  role ENUM('student','teacher','admin') NULL,
  class_id BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  chapter_id BIGINT UNSIGNED NULL,
  topic_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  page_views INT DEFAULT 0,
  resource_views INT DEFAULT 0,
  simulation_starts INT DEFAULT 0,
  simulation_completions INT DEFAULT 0,
  memory_reviews INT DEFAULT 0,
  drill_attempts INT DEFAULT 0,
  correct_answers INT DEFAULT 0,
  wrong_answers INT DEFAULT 0,
  mistake_count INT DEFAULT 0,
  chem_shastri_questions INT DEFAULT 0,
  total_time_seconds INT DEFAULT 0,
  enjoyment_score_avg DECIMAL(5,2) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY daily_learning_rollups_unique (rollup_date, user_id, class_id, chapter_id, topic_id, resource_id),
  KEY daily_learning_rollups_date_index (rollup_date),
  KEY daily_learning_rollups_user_index (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teacher_classrooms (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  teacher_user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(190) NOT NULL,
  class_level ENUM('9','10','11','12') NULL,
  subject VARCHAR(100) DEFAULT 'Chemistry',
  join_code VARCHAR(30) UNIQUE NULL,
  status ENUM('active','archived') DEFAULT 'active',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY teacher_classrooms_uuid_unique (uuid),
  KEY teacher_classrooms_teacher_user_id_index (teacher_user_id),
  CONSTRAINT teacher_classrooms_teacher_fk FOREIGN KEY (teacher_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS classroom_students (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  classroom_id BIGINT UNSIGNED NOT NULL,
  student_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('active','removed','pending') DEFAULT 'active',
  joined_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY classroom_students_unique (classroom_id, student_user_id),
  KEY classroom_students_student_index (student_user_id),
  CONSTRAINT classroom_students_classroom_fk FOREIGN KEY (classroom_id) REFERENCES teacher_classrooms(id) ON DELETE CASCADE,
  CONSTRAINT classroom_students_student_fk FOREIGN KEY (student_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teacher_assignments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(64) NOT NULL,
  teacher_user_id BIGINT UNSIGNED NOT NULL,
  classroom_id BIGINT UNSIGNED NULL,
  resource_id BIGINT UNSIGNED NULL,
  deck_id BIGINT UNSIGNED NULL,
  drill_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL,
  instructions TEXT NULL,
  due_at DATETIME NULL,
  status ENUM('draft','assigned','archived') DEFAULT 'draft',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY teacher_assignments_uuid_unique (uuid),
  KEY teacher_assignments_teacher_index (teacher_user_id),
  KEY teacher_assignments_classroom_index (classroom_id),
  CONSTRAINT teacher_assignments_teacher_fk FOREIGN KEY (teacher_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT teacher_assignments_classroom_fk FOREIGN KEY (classroom_id) REFERENCES teacher_classrooms(id) ON DELETE SET NULL,
  CONSTRAINT teacher_assignments_resource_fk FOREIGN KEY (resource_id) REFERENCES learning_resources(id) ON DELETE SET NULL,
  CONSTRAINT teacher_assignments_deck_fk FOREIGN KEY (deck_id) REFERENCES memory_decks(id) ON DELETE SET NULL,
  CONSTRAINT teacher_assignments_drill_fk FOREIGN KEY (drill_id) REFERENCES quick_drills(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS assignment_progress (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  assignment_id BIGINT UNSIGNED NOT NULL,
  student_user_id BIGINT UNSIGNED NOT NULL,
  status ENUM('not_started','in_progress','completed') DEFAULT 'not_started',
  score DECIMAL(5,2) NULL,
  completed_at DATETIME NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY assignment_progress_unique (assignment_id, student_user_id),
  KEY assignment_progress_student_index (student_user_id),
  CONSTRAINT assignment_progress_assignment_fk FOREIGN KEY (assignment_id) REFERENCES teacher_assignments(id) ON DELETE CASCADE,
  CONSTRAINT assignment_progress_student_fk FOREIGN KEY (student_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
