import type { RedoxAssetEntry, RedoxAssetRole } from "./redoxTypes";

export const redoxAssetManifest: Record<RedoxAssetRole, RedoxAssetEntry> = {
  story_confused_kitchen: {
    role: "story_confused_kitchen",
    label: "Confused kitchen opening",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_41 AM (1).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_41 AM (1).png",
    src: "/assets/redox-transfer-kitchen/web/story-confused-kitchen.webp",
    kind: "story",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "story",
    note: "Opening table frame with confused Karthik and Paati nearby.",
  },
  story_empty_kitchen: {
    role: "story_empty_kitchen",
    label: "Readable empty kitchen",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_41 AM (2).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_41 AM (2).png",
    src: "/assets/redox-transfer-kitchen/web/story-empty-kitchen.webp",
    kind: "story",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "story",
    note: "Clean kitchen background for equations and readable overlays.",
  },
  karthik_confused_character: {
    role: "karthik_confused_character",
    label: "Karthik confused",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_42 AM (3).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_42 AM (3).png",
    src: "/assets/redox-transfer-kitchen/processed/karthik-confused-character.png",
    kind: "character",
    width: 1086,
    height: 1448,
    hasAlpha: false,
    checkerboardSuspected: true,
    usedIn: "story-character",
    note: "Raw file had baked checkerboard; production uses processed transparent output.",
  },
  karthik_realization_character: {
    role: "karthik_realization_character",
    label: "Karthik realization",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_42 AM (4).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_42 AM (4).png",
    src: "/assets/redox-transfer-kitchen/processed/karthik-realization-character.png",
    kind: "character",
    width: 1086,
    height: 1448,
    hasAlpha: false,
    checkerboardSuspected: true,
    usedIn: "story-character",
    note: "Raw file had baked checkerboard; production uses processed transparent output.",
  },
  paati_explaining_character: {
    role: "paati_explaining_character",
    label: "Jaya Paati explaining",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_42 AM (5).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_42 AM (5).png",
    src: "/assets/redox-transfer-kitchen/processed/paati-explaining-character.png",
    kind: "character",
    width: 1086,
    height: 1448,
    hasAlpha: false,
    checkerboardSuspected: true,
    usedIn: "story-character",
    note: "Raw file had baked checkerboard; production uses processed transparent output.",
  },
  paati_giving_murukku_character: {
    role: "paati_giving_murukku_character",
    label: "Jaya Paati gives murukku",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_43 AM (6).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_43 AM (6).png",
    src: "/assets/redox-transfer-kitchen/processed/paati-giving-murukku-character.png",
    kind: "character",
    width: 1086,
    height: 1448,
    hasAlpha: false,
    checkerboardSuspected: true,
    usedIn: "story-character",
    note: "Raw file had baked checkerboard; production uses processed transparent output.",
  },
  story_guidance_kitchen: {
    role: "story_guidance_kitchen",
    label: "Paati guidance kitchen",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_43 AM (7).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_43 AM (7).png",
    src: "/assets/redox-transfer-kitchen/web/story-guidance-kitchen.webp",
    kind: "story",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "story",
    note: "Guidance scene with Paati teaching at the table.",
  },
  transition_kitchen_to_science: {
    role: "transition_kitchen_to_science",
    label: "Kitchen to science transition",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_44 AM (8).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_44 AM (8).png",
    src: "/assets/redox-transfer-kitchen/web/transition-kitchen-to-science.webp",
    kind: "story",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "story",
    note: "Magical warm kitchen-to-blue chemistry transition.",
  },
  redox_game_board_background: {
    role: "redox_game_board_background",
    label: "3D redox game board",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_44 AM (9).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_44 AM (9).png",
    src: "/assets/redox-transfer-kitchen/web/redox-game-board-background.webp",
    kind: "game",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "game",
    note: "Science-console background; interactive atoms and labels are rendered in code.",
  },
  redox_success_or_magic_background: {
    role: "redox_success_or_magic_background",
    label: "Success magic background",
    rawFile: "ChatGPT Image Jun 13, 2026, 01_01_45 AM (10).png",
    rawSrc: "/assets/redox-transfer-kitchen/raw/ChatGPT Image Jun 13, 2026, 01_01_45 AM (10).png",
    src: "/assets/redox-transfer-kitchen/web/redox-success-or-magic-background.webp",
    kind: "success",
    width: 1672,
    height: 941,
    hasAlpha: false,
    checkerboardSuspected: false,
    usedIn: "success",
    note: "Warm completion frame for badge and final redox mastery.",
  },
};

export const redoxAssetRoles = Object.keys(redoxAssetManifest) as RedoxAssetRole[];

export function getRedoxAsset(role: RedoxAssetRole) {
  return redoxAssetManifest[role];
}
