import type { RedoxChallengeQuestion, RedoxLevel, RedoxStoryFrame } from "./redoxTypes";

export const redoxStoryFrames: RedoxStoryFrame[] = [
  {
    id: "karthik_confused",
    assetRole: "story_confused_kitchen",
    speaker: "Karthik",
    text: "Paati, my textbook says oxidation and reduction are inseparable. How can two opposite things happen at the same time?",
    voiceText: "Paati, my textbook says oxidation and reduction are inseparable. How can two opposite things happen at the same time?",
    cameraMotion: "slow_zoom",
    duration: 7000,
  },
  {
    id: "paati_murukku_notice",
    assetRole: "story_guidance_kitchen",
    speaker: "Jaya Paati",
    text: "Aiyo, Kanna, don’t make your face like a squeezed lemon. It is like me giving you this murukku.",
    voiceText: "Aiyo, Kanna, don't make your face like a squeezed lemon. It is like me giving you this murukku.",
    cameraMotion: "pan_right",
    duration: 6500,
  },
  {
    id: "murukku_transfer",
    assetRole: "story_empty_kitchen",
    speaker: "Jaya Paati",
    text: "When I give, I lose the murukku. You gain it at the same moment. One transfer, two changes.",
    voiceText: "When I give, I lose the murukku. You gain it at the same moment. One transfer, two changes.",
    cameraMotion: "none",
    duration: 6500,
    overlay: "murukku_transfer",
    characterRoles: ["paati_giving_murukku_character", "karthik_confused_character"],
  },
  {
    id: "spectator_equation",
    assetRole: "story_empty_kitchen",
    speaker: "Jaya Paati",
    text: "In redox, electrons are transferred. Sulphate simply watches, so we remove it to see the real exchange.",
    voiceText: "In redox, electrons are transferred. Sulphate simply watches, so we remove it to see the real exchange.",
    cameraMotion: "slow_zoom",
    duration: 7000,
    overlay: "equation_strip",
    characterRoles: ["paati_explaining_character", "karthik_realization_character"],
  },
  {
    id: "kitchen_to_science",
    assetRole: "transition_kitchen_to_science",
    speaker: "Jaya Paati",
    text: "Now watch the real drama. Zinc gives. Copper receives.",
    voiceText: "Now watch the real drama. Zinc gives. Copper receives.",
    cameraMotion: "slow_zoom",
    duration: 6500,
  },
  {
    id: "start_game",
    assetRole: "redox_game_board_background",
    speaker: "Chemlab",
    text: "Start the Electron Exchange Table and make the transfer visible.",
    voiceText: "Start the Electron Exchange Table and make the transfer visible.",
    cameraMotion: "none",
    duration: 4500,
    overlay: "start_game",
  },
];

export const redoxLevels: RedoxLevel[] = [
  {
    id: "murukku_transaction",
    title: "Murukku Transfer",
    learningGoal: "Understand that transfer means one side loses and the other gains at the same moment.",
    objective: "Click the button to give murukku from Paati to Karthik.",
    paatiHint: "One button. One transfer. Watch both counters change together.",
    chemistryExplanation: "This prepares the redox idea: one species loses electrons while another gains them.",
    successMessage: "When Paati loses murukku, Karthik gains murukku. Losing and gaining are not separate events.",
    xp: 50,
    interactions: ["Give murukku"],
  },
  {
    id: "electron_transaction",
    title: "Electron Transaction Preview",
    learningGoal: "Map the murukku transfer to electron transfer.",
    objective: "Move the two electrons from zinc to copper ion.",
    equation: "Zn + Cu²⁺ → Zn²⁺ + Cu",
    paatiHint: "Murukku was the snack. Now electrons are the coins. Zinc gives, copper ion receives.",
    chemistryExplanation: "Zinc loses two electrons and copper ion gains those same two electrons. This single transfer is the redox transaction.",
    successMessage: "Zinc lost electrons. Copper ion gained electrons. This is redox.",
    xp: 80,
    interactions: ["Transfer electrons"],
  },
  {
    id: "oxidation_gate",
    title: "Oxidation Gate",
    learningGoal: "Understand oxidation as loss of electrons.",
    objective: "Zinc lost electrons. Choose what this is called.",
    equation: "Zn → Zn²⁺ + 2e⁻",
    paatiHint: "LEO: Loss of Electrons is Oxidation. Zinc is the giver.",
    chemistryExplanation: "Zinc loses two electrons, becomes Zn²⁺, and is oxidized.",
    successMessage: "Loss of Electrons = Oxidation. LEO badge unlocked.",
    xp: 90,
    interactions: ["Choose Lost electrons"],
  },
  {
    id: "reduction_gate",
    title: "Reduction Gate",
    learningGoal: "Understand reduction as gain of electrons.",
    objective: "Copper ion gained electrons. Choose what this is called.",
    equation: "Cu²⁺ + 2e⁻ → Cu",
    paatiHint: "GER: Gain of Electrons is Reduction. Copper ion is the receiver.",
    chemistryExplanation: "Copper ion gains two electrons and becomes neutral copper metal, so it is reduced.",
    successMessage: "Gain of Electrons = Reduction. GER badge unlocked.",
    xp: 90,
    interactions: ["Choose Gained electrons"],
  },
  {
    id: "spectator_cleanup",
    title: "Spectator Ion Cleanup",
    learningGoal: "Identify sulphate as a spectator ion after the electron transfer is clear.",
    objective: "Tap the sulphate ions that appear unchanged on both sides.",
    equation: "Zn + CuSO₄ → ZnSO₄ + Cu",
    paatiHint: "SO₄²⁻ appears on both sides. It is present, but it does not join the electron transaction.",
    chemistryExplanation: "The spectator ion is SO₄²⁻, so the net ionic reaction is Zn + Cu²⁺ → Zn²⁺ + Cu.",
    successMessage: "Good eye. SO₄²⁻ moved to the spectator gallery, leaving the net ionic reaction.",
    xp: 70,
    interactions: ["Tap both SO₄²⁻ ions"],
  },
  {
    id: "simultaneous_redox",
    title: "Redox Happens Together",
    learningGoal: "See oxidation and reduction as one linked electron-transfer transaction.",
    objective: "Run the reaction and watch oxidation and reduction happen together.",
    equation: "Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)",
    paatiHint: "Do not separate the story. Zinc gives only because copper ion receives.",
    chemistryExplanation: "Oxidation and reduction are inseparable because electrons lost by zinc are gained by copper ion.",
    successMessage: "One electron transfer creates both events.",
    xp: 110,
    interactions: ["Run Redox Reaction"],
  },
  {
    id: "agents_challenge",
    title: "Agents Challenge",
    learningGoal: "Identify what is oxidized, reduced, and which species acts as each agent.",
    objective: "Answer Paati’s redox agent questions.",
    equation: "Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)",
    paatiHint: "The chemical that gets oxidized acts as reducing agent. The chemical that gets reduced acts as oxidizing agent.",
    chemistryExplanation: "Zinc is oxidized and acts as reducing agent. Copper ion is reduced and acts as oxidizing agent.",
    successMessage: "Beautiful. You connected the changes to the agents.",
    xp: 140,
    interactions: ["Answer agent questions"],
  },
];

export const redoxAgentQuestions: RedoxChallengeQuestion[] = [
  {
    id: "oxidized",
    prompt: "Who is oxidized?",
    options: ["Zinc", "Copper ion", "Sulphate"],
    correctAnswer: "Zinc",
    explanation: "Zinc loses two electrons, so zinc is oxidized.",
  },
  {
    id: "reduced",
    prompt: "Who is reduced?",
    options: ["Zinc", "Copper ion", "Sulphate"],
    correctAnswer: "Copper ion",
    explanation: "Cu²⁺ gains two electrons and becomes Cu, so copper ion is reduced.",
  },
  {
    id: "reducing_agent",
    prompt: "Who causes copper ion to be reduced?",
    options: ["Zinc", "Copper ion", "Sulphate"],
    correctAnswer: "Zinc",
    explanation: "Zinc gives electrons to copper ion, so zinc is the reducing agent.",
  },
  {
    id: "oxidizing_agent",
    prompt: "Who causes zinc to be oxidized?",
    options: ["Zinc", "Copper ion", "Sulphate"],
    correctAnswer: "Copper ion",
    explanation: "Copper ion accepts zinc’s electrons, so copper ion is the oxidizing agent.",
  },
];

export const redoxFinalSummary = {
  badge: "Redox Transfer Master",
  equation: "Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)",
  points: [
    "Zinc loses two electrons and becomes Zn²⁺.",
    "Copper ion gains two electrons and becomes Cu.",
    "SO₄²⁻ is a spectator ion in this reaction.",
    "Zinc is the reducing agent because it causes copper ion to be reduced.",
    "Copper ion is the oxidizing agent because it causes zinc to be oxidized.",
  ],
};
